name: Generate Snake

on:
  # Roda automaticamente a cada 24 horas
  schedule:
    - cron: "0 */24 * * *" 
  
  # Permite rodar manualmente na aba "Actions"
  workflow_dispatch:

# Permissões necessárias para gravar a imagem no repositório
permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checa o código do repositório
      - uses: actions/checkout@v3
      
      # Gera a animação da cobrinha (SVG)
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # Salva o arquivo SVG
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          # Token secreto do GitHub (já vem configurado)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Envia o arquivo gerado para uma branch separada chamada "output"
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
